/**
 * Play of the Day — one editorially-selected pick, posted once daily, the
 * same for every user that day.
 *
 * Timing: the target is 8am ET most days, but an early match (say tennis at
 * 6am ET) would already be underway by then, so the evening before (7pm ET)
 * gets first crack at anything starting before MORNING_CUTOFF_HOUR the next
 * day. Cloudflare Cron Triggers are UTC-only and the target times are ET
 * wall-clock, which shift by an hour across DST — rather than hand-maintain
 * two UTC crons that need updating twice a year, the trigger fires hourly and
 * this module checks the current ET hour itself (see shouldRunNow), which
 * self-corrects across DST automatically.
 *
 * Storage: Workers KV, one key per ET calendar date. Once a date's pick is
 * written, nothing overwrites it — an early-match pick from the evening
 * before is never bumped by the next morning's run, and a morning pick is
 * never regenerated by a later hourly tick that day. "Consistent all day" is
 * enforced by this idempotency check, not by only running once.
 */

import { analyze, RULES, explainExtensive, formatAmerican, suggestedStake } from '../../docs/engine.js';
import { buildInsights, insightsByTier, isTennis, isMma } from '../../docs/insights.js';
import { fetchContext, hasContext } from './context.js';
import { fetchWeather } from './weather.js';
import { fetchMmaContext } from './mma.js';

const ET_TZ = 'America/New_York';
const MORNING_HOUR = 8;         // run window: 8am ET
const EVENING_HOUR = 19;        // run window: 7pm ET, for the next day's early games
const MORNING_CUTOFF_HOUR = 9;  // a game before this ET hour is "too early" for the morning slot

const TENNIS_ARCHIVE_BASE = 'https://miguelsgarcia4.github.io/PerpetualCode/data';

/** ET calendar date (YYYY-MM-DD) and wall-clock hour for a given instant. */
function etParts(ms) {
  const fmt = new Intl.DateTimeFormat('en-US', {
    timeZone: ET_TZ,
    year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', hour12: false,
  });
  const parts = Object.fromEntries(fmt.formatToParts(ms).map((p) => [p.type, p.value]));
  // Intl reports hour 24 for midnight in some environments — normalise to 0.
  const hour = Number(parts.hour) % 24;
  return { date: `${parts.year}-${parts.month}-${parts.day}`, hour };
}

/** The ET calendar date N days after the date containing `ms`. */
function etDatePlusDays(ms, days) {
  return etParts(ms + days * 86400000).date;
}

/**
 * Whether this hourly tick should do real work, and which phase. Only ever
 * one of these is true for a given hour — they're different ET hours by
 * definition (8 vs 19) — so there's no ambiguity about which phase fired.
 */
export function currentPhase(now = Date.now()) {
  const { hour } = etParts(now);
  if (hour === MORNING_HOUR) return 'morning';
  if (hour === EVENING_HOUR) return 'evening-early';
  return null;
}

/**
 * Candidates eligible for a given phase's target date and time window.
 * Morning: today's games from the cutoff hour onward. Evening-early:
 * tomorrow's games before the cutoff hour — the ones morning would miss
 * entirely by the time it runs.
 */
function eligibleForPhase(candidates, phase, now) {
  const targetDate = phase === 'morning' ? etParts(now).date : etDatePlusDays(now, 1);
  return candidates.filter((c) => {
    const { date, hour } = etParts(c.commenceMs);
    if (date !== targetDate) return false;
    return phase === 'morning' ? hour >= MORNING_CUTOFF_HOUR : hour < MORNING_CUTOFF_HOUR;
  });
}

/** The KV date key this phase's pick belongs to — see eligibleForPhase. */
function targetDateFor(phase, now) {
  return phase === 'morning' ? etParts(now).date : etDatePlusDays(now, 1);
}

/**
 * One Play of the Day per major sport, alongside the single overall pick
 * above. Each bucket maps to real Odds API sport_key prefixes rather than one
 * exact key — tennis in particular is keyed per-tournament
 * (tennis_atp_wimbledon, tennis_wta_us_open, ...), never one blanket
 * "tennis_atp" key, so a prefix match is what actually finds anything.
 */
const SPORT_BUCKETS = [
  { key: 'nfl', label: 'NFL', match: (s) => s === 'americanfootball_nfl' },
  { key: 'mlb', label: 'MLB', match: (s) => s === 'baseball_mlb' },
  { key: 'nba', label: 'NBA', match: (s) => s === 'basketball_nba' },
  { key: 'wnba', label: 'WNBA', match: (s) => s === 'basketball_wnba' },
  { key: 'nhl', label: 'NHL', match: (s) => s === 'icehockey_nhl' },
  { key: 'mma', label: 'MMA', match: (s) => isMma(s) },
  { key: 'atp', label: "Tennis (ATP)", match: (s) => /^tennis_atp/i.test(s) },
  { key: 'wta', label: "Tennis (WTA)", match: (s) => /^tennis_wta/i.test(s) },
];

/**
 * Filters out exhibition-format games that happen to carry a real, gradeable
 * price but aren't a real competitive game — an All-Star Game or Pro Bowl
 * has odds priced on it same as anything else, but nobody wants it standing
 * in as "today's NBA/NFL pick." The Odds API carries no explicit game-type
 * field to key off, so this reads the only text available: the team names
 * themselves, which for these formats aren't real team names at all (e.g.
 * "Team LeBron", "AFC", "NL All-Stars").
 */
const EXHIBITION_PATTERN = /all[\s-]?star|pro\s?bowl|dunk contest|3-point contest|three-point contest|skills challenge|summer league|rising stars|g league|celebrity|exhibition/i;
// NBA/NHL All-Star Games are draft-captain squads named "Team LeBron" or
// "Team McDavid" rather than a real franchise name — a real team is never
// named "Team <FirstName>", so this catches the actual naming pattern those
// games use in the odds feed, which the keyword list above doesn't.
const CAPTAIN_TEAM_PATTERN = /^team [a-z.'-]+$/i;
function isExhibition(candidate) {
  const names = [candidate.home, candidate.away];
  return names.some((n) => EXHIBITION_PATTERN.test(n) || CAPTAIN_TEAM_PATTERN.test(n));
}

let tennisArchiveCache = null; // module-scope: survives across requests in the same isolate
async function loadTennisArchive(sportKey) {
  const tour = /wta/i.test(sportKey) ? 'wta' : 'atp';
  tennisArchiveCache ??= {};
  if (tennisArchiveCache[tour]) return tennisArchiveCache[tour];

  try {
    const r = await fetch(`${TENNIS_ARCHIVE_BASE}/tennis-${tour}.json`);
    tennisArchiveCache[tour] = r.ok ? await r.json() : null;
  } catch {
    tennisArchiveCache[tour] = null;
  }
  return tennisArchiveCache[tour];
}

/** Reconstruct the same {leg, home/away subject} buildInsights expects. */
function legFromCandidate(c) {
  return {
    sportKey: c.sportKey,
    marketKey: c.marketKey,
    selection: c.selection,
    home: c.home,
    away: c.away,
    eventId: c.eventId,
  };
}

async function researchFor(candidate, env, ctx) {
  const leg = legFromCandidate(candidate);
  try {
    if (isTennis(candidate.sportKey)) {
      const tennisData = await loadTennisArchive(candidate.sportKey);
      return buildInsights(leg, { tennisData });
    }
    if (isMma(candidate.sportKey)) {
      const subject = candidate.selection.replace(/ to win$/i, '').trim();
      const mmaContext = await fetchMmaContext(
        { fighterA: candidate.home, fighterB: candidate.away }, ctx,
      );
      return buildInsights(leg, { mmaContext });
    }
    if (hasContext(candidate.sportKey)) {
      const [context, weather] = await Promise.all([
        fetchContext(
          { sportKey: candidate.sportKey, home: candidate.home, away: candidate.away }, ctx,
        ),
        fetchWeather(
          { sportKey: candidate.sportKey, homeTeam: candidate.home, commenceMs: candidate.commenceMs }, ctx,
        ),
      ]);
      return buildInsights(leg, { context, weather });
    }
  } catch {
    /* Research is a bonus on the write-up, not a blocker for posting it. */
  }
  return [];
}

/**
 * The full breakdown write-up for one candidate, in four named tiers:
 *
 *   1. The Market & Price Case — the same no-vig/EV reasoning every pick
 *      card carries, just not truncated to one sentence.
 *   2. Primary Personnel & Direct Matchup — the subject's own record, form,
 *      head-to-head, and (MMA) finish tendencies.
 *   3. Supporting Cast & Availability — team-sport roster availability only;
 *      omitted entirely for tennis and MMA, which have no supporting cast to
 *      report on rather than an empty placeholder pretending otherwise.
 *   4. Situational Notes — layoff / retirement-and-walkover flags, the only
 *      "is this record still current" signal this app's sources carry. Not
 *      labelled "Environmental" — there is no weather, travel, or venue data
 *      behind this app at all, and claiming that coverage would be exactly
 *      the kind of invented authority this app's own research module refuses
 *      to produce.
 *
 * Each tier is included only when it actually has content — an empty section
 * with a heading and nothing under it reads as a gap the analysis missed,
 * not as an honest "nothing sourced here."
 */
function buildWriteup(candidate, research, now) {
  const priceBullets = explainExtensive(candidate, { now });
  const headline = `${candidate.selection} (${formatAmerican(candidate.american)})`;
  const matchup = `${candidate.away} @ ${candidate.home}`;

  const personnel = insightsByTier(research, 'personnel');
  const supporting = insightsByTier(research, 'supporting');
  // Environmental (weather, NFL/MLB only) and situational (a layoff or
  // currency flag, tennis/MMA only) are separate tags at the source — they
  // answer different questions — but in practice a given sport only ever
  // populates one of the two, so the write-up presents them under one
  // combined heading rather than two headings where one is nearly always
  // empty. Environmental first: it's about the game itself, before notes
  // about a specific competitor's recent history.
  const environmental = [
    ...insightsByTier(research, 'environmental'),
    ...insightsByTier(research, 'situational'),
  ];

  return {
    headline,
    matchup,
    sportTitle: candidate.sportTitle ?? candidate.sportKey,
    marketLabel: candidate.marketLabel,
    price: formatAmerican(candidate.american),
    book: candidate.book,
    score: Math.round(candidate.score),
    commenceMs: candidate.commenceMs,
    stake: suggestedStake(candidate),
    sections: [
      { title: 'The Market & Price Case', bullets: priceBullets },
      ...(personnel.length ? [{ title: 'Primary Personnel & Direct Matchup', bullets: personnel }] : []),
      ...(supporting.length ? [{ title: 'Supporting Cast & Availability', bullets: supporting }] : []),
      ...(environmental.length ? [{ title: 'Environmental & Situational Notes', bullets: environmental }] : []),
    ],
  };
}

async function buildRecord(best, phase, dateKey, now, env, ctx) {
  const research = await researchFor(best, env, ctx);
  const writeup = buildWriteup(best, research, now);
  return {
    date: dateKey,
    phase,
    generatedAt: now,
    pick: {
      id: best.id, sportKey: best.sportKey, marketKey: best.marketKey,
      selection: best.selection, american: best.american, score: best.score,
      home: best.home, away: best.away, commenceMs: best.commenceMs, book: best.book,
    },
    writeup,
  };
}

/**
 * Run one phase's selection: pull the board, filter to this phase's time
 * window (and out any exhibition-format game — see isExhibition), take the
 * single best-graded candidate overall, build its write-up, and store it —
 * unless that date's KV entry already exists, in which case the overall pick
 * has nothing to do (either it already ran today, or the evening before
 * already claimed the date for an early match).
 *
 * Each major sport (SPORT_BUCKETS) gets the same treatment independently,
 * under its own KV key — a sport whose only game today is a WNBA All-Star
 * Game, or that has nothing on the board at all, simply has no entry for
 * that date, rather than a placeholder standing in for a game that isn't
 * really there.
 */
export async function runPotdPhase(phase, { env, ctx, now = Date.now(), fetchBoard }) {
  const dateKey = targetDateFor(phase, now);
  const kvKey = `potd:${dateKey}`;

  const events = await fetchBoard();
  const candidates = analyze(events, { now });
  const pool = candidates.filter((c) => c.score >= RULES.MIN_SCORE && !isExhibition(c));
  const eligible = eligibleForPhase(pool, phase, now);

  const existing = await env.POTD_KV.get(kvKey);
  let mainResult;
  if (existing) {
    mainResult = { skipped: true, reason: 'already generated', dateKey };
  } else if (!eligible.length) {
    mainResult = { skipped: true, reason: 'no qualifying candidate in this phase\'s window', dateKey };
  } else {
    const best = eligible.reduce((a, b) => (b.score > a.score ? b : a));
    const record = await buildRecord(best, phase, dateKey, now, env, ctx);
    // A day's pick, once posted, doesn't move even if the market does — it's
    // an editorial call made at a point in time, not a live-repriced candidate.
    await env.POTD_KV.put(kvKey, JSON.stringify(record), { expirationTtl: 86400 * 8 });
    mainResult = { skipped: false, dateKey, pick: record.pick };
  }

  const bySport = {};
  for (const bucket of SPORT_BUCKETS) {
    const bucketKey = `potd:${dateKey}:sport:${bucket.key}`;
    const alreadyDone = await env.POTD_KV.get(bucketKey);
    if (alreadyDone) {
      bySport[bucket.key] = { skipped: true, reason: 'already generated' };
      continue;
    }

    const bucketEligible = eligible.filter((c) => bucket.match(c.sportKey));
    if (!bucketEligible.length) {
      bySport[bucket.key] = { skipped: true, reason: 'no qualifying candidate' };
      continue;
    }

    const best = bucketEligible.reduce((a, b) => (b.score > a.score ? b : a));
    const record = await buildRecord(best, phase, dateKey, now, env, ctx);
    record.sportLabel = bucket.label;
    await env.POTD_KV.put(bucketKey, JSON.stringify(record), { expirationTtl: 86400 * 8 });
    bySport[bucket.key] = { skipped: false, pick: record.pick };
  }

  return { ...mainResult, bySport };
}

/** Today's Play of the Day, or yesterday's as a labelled fallback if today's
 * hasn't been generated yet (e.g. it's 6am ET and neither cron has fired). */
export async function getPotd(env, now = Date.now()) {
  const today = etParts(now).date;
  const todayRaw = await env.POTD_KV.get(`potd:${today}`);
  if (todayRaw) return JSON.parse(todayRaw);

  const yesterday = etDatePlusDays(now, -1);
  const yesterdayRaw = await env.POTD_KV.get(`potd:${yesterday}`);
  if (yesterdayRaw) return { ...JSON.parse(yesterdayRaw), stale: true };

  return null;
}

/**
 * Today's per-sport Play of the Day picks, keyed by SPORT_BUCKETS' bucket
 * key. Each sport is read independently and falls back to yesterday's the
 * same way getPotd does — a sport with nothing generated today (no game, an
 * off-season league, or every game filtered as exhibition) is simply absent
 * from the result, never a placeholder.
 */
export async function getPotdBySport(env, now = Date.now()) {
  const today = etParts(now).date;
  const yesterday = etDatePlusDays(now, -1);

  const results = await Promise.all(
    SPORT_BUCKETS.map(async (bucket) => {
      const todayRaw = await env.POTD_KV.get(`potd:${today}:sport:${bucket.key}`);
      if (todayRaw) return [bucket.key, JSON.parse(todayRaw)];

      const yesterdayRaw = await env.POTD_KV.get(`potd:${yesterday}:sport:${bucket.key}`);
      if (yesterdayRaw) return [bucket.key, { ...JSON.parse(yesterdayRaw), stale: true }];

      return [bucket.key, null];
    }),
  );

  return Object.fromEntries(results.filter(([, value]) => value != null));
}
